# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/saman-mb"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/saman_mb"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/saman.badak/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/samanb1/"

[social.params]
icon = "brand-linkedin"
